name: "Random reviwer"

on:
  pull_request:
    types:
      - opened
      - reopened
    branches: ['protectHeo','DGJSKIM', 'anjungin', 'unie11', 'realain']

permissions:
  pull-requests: write

jobs:
  random-reviwer:
    runs-on: ubuntu-latest
    steps:
      - id: random_reviewer
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const me = '${{ github.event.pull_request.user.login }}';
            const response = await github.rest.orgs.listMembers({
              org: context.repo.owner,  // ì¡°ì§ ì´ë¦„
            });
            
            const candidate = response.data.map(member => member.login);
            const candidateWithoutMe = candidate.filter(id => id !== me);
            
            function getRandomTwo(array) {
              if (array.length < 2) {
                throw new Error("Array must have at least two elements.");
              }
            
              const index1 = Math.floor(Math.random() * array.length);
              let index2;
            
              // ì²« ë²ˆì§¸ ì¸ë±ìŠ¤ì™€ ë‹¤ë¥¸ ê°’ì„ ì°¾ì„ ë•Œê¹Œì§€ ë°˜ë³µ
              do {
              index2 = Math.floor(Math.random() * array.length);
            } while (index1 === index2);
            
              return [array[index1], array[index2]];
            }
            
            const electedReviewers = getRandomTwo(candidateWithoutMe);
            const comment = `@${electedReviewers[0]} ë‹˜, @${electedReviewers[1]} ë‹˜ ìˆ­ê³ í•œ ëœë¤ ë¦¬ë·°ì–´ë¡œ ë‹¹ì²¨ë˜ì…¨ìŠµë‹ˆë‹¤! ë¦¬ë·°ë¥¼ ë¶€íƒë“œë¦½ë‹ˆë‹¤. ğŸ™`
            core.setOutput('reviewer_1', electedReviewers[0]);
            core.setOutput('reviewer_2', electedReviewers[1]);
            core.setOutput('comment', comment);

      - name: Create Pull Request Comment
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = "${{ steps.random_reviewer.outputs.comment }}";
            // Create comment 
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body : comment
            });

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Post to a Slack channel
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "text": "ğŸ‰ ì¶•í•˜í•©ë‹ˆë‹¤! \n\n *<${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>* ì˜ ë¦¬ë·°ì–´ë¡œ \n\n<@${{ steps.random_reviewer.outputs.reviewer_1 }}> ë‹˜ê³¼ <@${{ steps.random_reviewer.outputs.reviewer_2 }}> ë‹˜ì´ ë‹¹ì„ ë˜ì—ˆìŠµë‹ˆë‹¤! ğŸ‰"
          }' \
           ${{ secrets.SLACK_WEBHOOK }}
